#!/bin/bash
declare lv_char
declare -i lv_int
declare -i exit_code
declare -i counter=0
declare -i menu_item_count=4
declare selected_device      # Выбранный диск в формате для отображения
declare selected_disk        # Выбранный диск, например "/dev/sda"
declare selected_device_part # Выбранный раздел диска в формате для отображения
declare selected_part_size   # Размер выбранного раздела диска для отображения
declare selected_part        # Выбранный раздел диска, например "/dev/sda1"
declare lvfs=vfat            # Файловая система в которую форматируем диск
declare sel_dev_index=1

clear_sel_part()
{
  selected_device_part=""
  selected_part=""
  selected_part_size=""
}

parse()
{
 declare -i scnt=0
 declare s
# s="$1"
# echo "$s"
 for ((lnumber=1;lnumber<=50;lnumber++))
 do
   s="$(echo "$1" | cut -d " " -f"$lnumber")"
   if [ "$s" == "*" ]; then
    let scnt=scnt-1
   fi
   if [ "$s" != "" ]; then
    let scnt=scnt+1
    if [ "$scnt" -eq "$2" ]; then
      echo "$s"
      break
    fi
   fi
 done
}

get_input_charcode()
{
  if [ "$1" -eq 0 ]; then
    read -r -s -n 1 lv_char
    LC_ALL=C printf -v lv_int '%d' "'$lv_char"
  else
    read -r -s -n 1 -t 0.01 lv_char
    LC_ALL=C printf -v lv_int '%d' "'$lv_char"
  fi
}

init_device()
{
declare -i lvcntdev

echo -e "\e[44m"
clear
echo -e "\e[00m"

lvcntdev="$(lsscsi | wc -l)"
menu_item_count="$lvcntdev"

# echo "$lvcntdev"

for ((number=1;number<=$lvcntdev;number++))
do
  if [ "$number" -eq "$counter" ]; then
    echo -e "\e[41m$number. $(lsscsi | head -n $number | tail -n1)\e[00m"
    selected_disk="$(lsscsi | head -n $number | tail -n1 | tr " " "\n" | grep "/dev")"
    selected_device=" - $(fdisk -l "$selected_disk" | grep "Disk /dev" | cut -d "," -f1)"
    sel_dev_index="$number"
  else
    echo -e "\e[44m$number. $(lsscsi | head -n $number | tail -n1)\e[00m"
  fi
done
}

init_partition()
{
declare -i lvcntdev

echo -e "\e[44m"
clear
echo -e "\e[00m"

lvcntdev="$(fdisk -l $selected_disk | grep -E '^/dev/' | wc -l)"
menu_item_count="$lvcntdev"

# echo "$lvcntdev"

for ((number=1;number<=$lvcntdev;number++))
do
  if [ "$number" -eq "$counter" ]; then
    selected_device_part="$(fdisk -l $selected_disk | grep -E '^/dev/' | head -n $number | tail -n1)"
    echo -e "\e[41m$number. $selected_device_part\e[00m"
    selected_part="$(echo $selected_device_part | cut -d " " -f1)"
    selected_part_size="$(parse "$selected_device_part" 5)"
  else
    echo -e "\e[44m$number. $(fdisk -l $selected_disk | grep -E '^/dev/' | head -n $number | tail -n1)\e[00m"
  fi
  
done
}


print_menu()
{
 echo -e "\e[44m"
 clear
 echo -e "\e[00m"
 if [ "$menu_item_count" -eq 4 ]; then
   if [ "$counter" -eq 1 ]; then
     echo -e "\e[41m1. Выбрать диск $selected_device\e[00m"
   else
     echo -e "\e[44m1. Выбрать диск $selected_device\e[00m"
   fi
   if [ "$counter" -eq 2 ]; then
     echo -e "\e[41m2. Форматировать диск\e[00m"
   else
     echo -e "\e[44m2. Форматировать диск\e[00m"
   fi
   if [ "$counter" -eq 3 ]; then
     echo -e "\e[41m3. Установка\e[00m"
   else
     echo -e "\e[44m3. Установка\e[00m"
   fi
   if [ "$counter" -eq 4 ]; then
     echo -e "\e[41m4. Выход (Клавиша ESC)\e[00m"
   else
     echo -e "\e[44m4. Выход (Клавиша ESC)\e[00m"
   fi
 else
   if [ "$counter" -eq 1 ]; then
     echo -e "\e[41m1. Выбрать диск $selected_device\e[00m"
     
   else
     echo -e "\e[44m1. Выбрать диск $selected_device\e[00m"
   fi
   if [ "$counter" -eq 2 ]; then
     echo -e "\e[41m2. Выбрать раздел диска [ $selected_disk [ $selected_part $selected_part_size ]] \e[00m"
   else
     echo -e "\e[44m2. Выбрать раздел диска [ $selected_disk [ $selected_part $selected_part_size ]] \e[00m"
   fi
   if [ "$counter" -eq 3 ]; then
     echo -e "\e[41m3. Переразбить диск [ $selected_disk ] \e[00m"
   else
     echo -e "\e[44m3. Переразбить диск [ $selected_disk ] \e[00m"
   fi
   if [ "$counter" -eq 4 ]; then
     echo -e "\e[41m4. Форматировать диск [ $selected_disk [ $selected_part $selected_part_size ]] \e[00m"
   else
     echo -e "\e[44m4. Форматировать диск [ $selected_disk [ $selected_part $selected_part_size ]] \e[00m"
   fi
   if [ "$counter" -eq 5 ]; then
     echo -e "\e[41m5. Установка\e[00m"
   else
     echo -e "\e[44m5. Установка\e[00m"
   fi
   if [ "$counter" -eq 6 ]; then
     echo -e "\e[41m6. Выход (Клавиша ESC)\e[00m"
   else
     echo -e "\e[44m6. Выход (Клавиша ESC)\e[00m"
   fi
 fi
}

format_disk()
{
  menu_item_count=7
  echo -e "\e[44m"
  clear
  echo -e "\e[00m"
  
  if [ "$counter" -eq 1 ]; then
    echo -e "\e[41m1. Форматировать диск [ $selected_disk [ $selected_part $selected_part_size ]] в FAT32 \e[00m"
  else
    echo -e "\e[44m1. Форматировать диск [ $selected_disk [ $selected_part $selected_part_size ]] в FAT32 \e[00m"
  fi
  if [ "$counter" -eq 2 ]; then
    echo -e "\e[41m2. Форматировать диск [ $selected_disk [ $selected_part $selected_part_size ]] в EXT2 \e[00m"
  else
    echo -e "\e[44m2. Форматировать диск [ $selected_disk [ $selected_part $selected_part_size ]] в EXT2 \e[00m"
  fi
  if [ "$counter" -eq 3 ]; then
    echo -e "\e[41m3. Форматировать диск [ $selected_disk [ $selected_part $selected_part_size ]] в EXT3 \e[00m"
  else
    echo -e "\e[44m3. Форматировать диск [ $selected_disk [ $selected_part $selected_part_size ]] в EXT3 \e[00m"
  fi
  if [ "$counter" -eq 4 ]; then
    echo -e "\e[41m4. Форматировать диск [ $selected_disk [ $selected_part $selected_part_size ]] в EXT4 \e[00m"
  else
    echo -e "\e[44m4. Форматировать диск [ $selected_disk [ $selected_part $selected_part_size ]] в EXT4 \e[00m"
  fi
  if [ "$counter" -eq 5 ]; then
    echo -e "\e[41m5. Форматировать диск [ $selected_disk [ $selected_part $selected_part_size ]] в XFS \e[00m"
  else
    echo -e "\e[44m5. Форматировать диск [ $selected_disk [ $selected_part $selected_part_size ]] в XFS \e[00m"
  fi
  if [ "$counter" -eq 6 ]; then
    echo -e "\e[41m6. Форматировать диск [ $selected_disk [ $selected_part $selected_part_size ]] в REISERFS \e[00m"
  else
    echo -e "\e[44m6. Форматировать диск [ $selected_disk [ $selected_part $selected_part_size ]] в REISERFS \e[00m"
  fi
  if [ "$counter" -eq 7 ]; then
    echo -e "\e[41m7. Отмена \e[00m"
  else
    echo -e "\e[44m7. Отмена \e[00m"
  fi
}

confirm_format_disk()
{
  menu_item_count=2
  echo -e "\e[44m"
  clear
  echo -e "\e[00m"
  echo -e "\e[44mВы действительно хотите отформатировать диск? [ $selected_disk [ $selected_part $selected_part_size ]] \e[00m"
  echo -e "\e[00m"
  if [ "$counter" -eq 1 ]; then
    echo -e "\e[41m1. Да\e[00m"
  else
    echo -e "\e[44m1. Да\e[00m"
  fi
  if [ "$counter" -eq 2 ]; then
    echo -e "\e[41m2. Нет\e[00m"
  else
    echo -e "\e[44m2. Нет\e[00m"
  fi
}

exec_format_disk()
{
  menu_item_count=1
  echo -e "\e[00m"
  clear
  echo -e "\e[00m"
#  echo -n "$(dd if=/dev/zero of="$selected_part" bs=1M)" 
# Проверяем если диск смонтирован, то его надо размонтировать перед форматированием
  check_mount="$(mount -l | grep "$selected_part")"
  if [ "$check_mount" != "" ]; then
    umount "$selected_part"
  fi
  sleep 3
# Форматируем выбранный раздел
  if [ "$lvfs" == 'reiserfs' ]; then
    mkfs -t $lvfs -f -l "ALSY-REISERFS" "$selected_part"
  elif [ "$lvfs" == 'xfs' ]; then
    mkfs -t $lvfs -f -L "ALSY-XFS" "$selected_part"
  elif [ "$lvfs" == 'vfat' ]; then
    mkfs -t $lvfs -n "ALSY" "$selected_part"
  else
    mkfs -t $lvfs -L "ALSY-$lvfs" "$selected_part"
  fi
  if [ $? -eq 0 ]; then
   lverrtext="успешно"
  else
   lverrtext="с ошибкой"
  fi
# Выводим результат
  echo -e "\e[00m Форматирование диска выполнено $lverrtext [ $selected_disk [ $selected_part $selected_part_size ]] \e[00m"
  sleep 3
  read -n 1 -t 60 lvchar
}

navigate()
{
exit_code=0
exit_flg=1
counter=1

if [ "$curr_scenario" -eq 2 ]; then
  counter="$sel_dev_index"
fi

# Если выбран пункт "Форматировать" но не выбран раздел диска
if [[ "$curr_scenario" -eq 4 && $selected_part == "" ]]; then
  curr_scenario=3
  next_scenario=4
  exit_flg=0
fi

while [[ "$exit_code" -eq 0 || "$exit_flg" -eq 0 ]]
do

if [[ "$exit_code" -ne 0 && "$exit_flg" -eq 0 ]]; then
  exit_flg=1
  exit_code=0
  curr_scenario="$next_scenario"
  counter=1
fi

# Выводим меню
if [ "$curr_scenario" -eq 1 ]; then
  print_menu
elif [ "$curr_scenario" -eq 3 ]; then
  init_partition
elif [ "$curr_scenario" -eq 4 ]; then
  format_disk
elif [[ "$curr_scenario" -ge 41 && "$curr_scenario" -le 46 ]]; then
  confirm_format_disk
else
  init_device
fi
# Считываем один символ с клавиатуры
get_input_charcode "0"
if [ "$lv_int" -eq 0 ]; then
 exit_code="$counter"
 continue
fi
# Если это не печатный символ ESC, UP ARROW, DOWN ARROW,..., etc
if [ "$lv_int" -eq 27 ]; then 
 get_input_charcode "1"
 if [ "$lv_int" -ne 91 ]; then
  # Этот символ ESCAPE
  exit_code=999
  continue
 fi
# В противном случае этот символ одна из стрелок вверх или вниз или вправо или влево
 get_input_charcode "1"
 if [[ "$lv_int" -eq 65 && "$counter" -gt 1 ]]; then
  let counter=counter-1
 else
  if [ "$lv_int" -eq 65 ]; then
    counter="$menu_item_count"
  fi
 fi
 if [[ "$lv_int" -eq 66 && "$counter" -lt "$menu_item_count" ]]; then
  let counter=counter+1
 else
  if [ "$lv_int" -eq 66 ]; then
    counter=1
  fi
 fi
# echo -n -e "$counter\b"
# echo "$lv_int"
fi
done
}

# ***  Отсюда начинается выполнение ***
declare -i main_exit_code=0

while [ "$main_exit_code" -eq 0 ]
do
  curr_scenario=1
  if [ "$selected_disk" != "" ]; then
    menu_item_count=6
  else
    menu_item_count=4
  fi
  navigate
  if [ "$exit_code" -eq 999 ]; then
      main_exit_code="$counter"
      continue
  fi
  # Выбрать пункт 1. меню - "Выбрать диск"
  if [ "$counter" -eq 1 ]; then
    clear_sel_part
    curr_scenario=2
    navigate
    continue
  else
    # Выбрать пункт 2. меню - "Форматировать"
    if [[ "$counter" -eq 2 && "$selected_disk" == "" ]]; then  
      curr_scenario=2
      navigate
      continue
    fi
    # Выбран пункт 2. меню - "Выбрать раздел диска"
    if [[ "$counter" -eq 2 && "$selected_disk" != "" ]]; then
      curr_scenario=3
      navigate
      continue
    fi
    # Выбран пункт 3. меню - "Установка"
    if [[ "$counter" -eq 3 && "$selected_disk" == "" ]]; then
      curr_scenario=2
      navigate
      continue
    fi
    # Выбран пункт 3. меню - "Переразбить диск"
    if [[ "$counter" -eq 3 && "$selected_disk" != "" ]]; then
      echo -e "\e[00m"
      clear
      echo "select 3 item menu"
      fdisk $selected_disk
      clear_sel_part
      continue
    fi
    # Выбран пункт 4. меню - "Выход"
    if [[ "$counter" -eq 4 && "$selected_disk" == "" ]]; then
      main_exit_code="$counter"
      clear
      echo "counter=$counter"
      continue
    fi
    # Выбран пункт 4. меню - "Форматировать диск"
    if [[ "$counter" -eq 4 && "$selected_disk" != "" ]]; then
      curr_scenario=4
      navigate
      # После выбора пункта меню анализируем что выбрано и в зависимости от этого выводим следющ меню
      if [ "$counter" -eq 1 ]; then
        curr_scenario=41
        lvfs="vfat"
        navigate
      elif [ "$counter" -eq 2 ]; then
        curr_scenario=42
        lvfs="ext2"
        navigate
      elif [ "$counter" -eq 3 ]; then
        curr_scenario=43
        lvfs="ext3"
        navigate
      elif [ "$counter" -eq 4 ]; then
        curr_scenario=44
        lvfs="ext4"
        navigate
      elif [ "$counter" -eq 5 ]; then
        curr_scenario=45
        lvfs="xfs"
        navigate
      elif [ "$counter" -eq 6 ]; then
        curr_scenario=46
        lvfs="reiserfs"
        navigate
      fi 
      # После выбора пункта меню анализируем что выбрано и в зависимости от этого выполняем или нет форматирование диска
      if [ "$counter" -eq 1 ]; then
        exec_format_disk
        sleep 1
      fi
      continue
    fi
    # Выбран пункт 6. меню - "Выход"
    if [[ "$counter" -eq 6 && "$selected_disk" != "" ]]; then
      main_exit_code="$counter"
      clear
      echo "counter=$counter"
      continue
    fi
  fi
done
# Очистка экрана
echo -e "\e[00m"
clear