#!/bin/sh
# Initial script for Linux Live Kit
# Author: Tomas M <http://www.linux-live.org/>
# Modified by: Sevastyanov S.V. for ALSY-LINUX 28.01.2020

export PATH=.:/:/usr/sbin:/usr/bin:/sbin:/bin

. /lib/.config
. /lib/livekitlib

init_values
transfer_initramfs

MEMORY=/memory
CHANGES=$MEMORY/changes
UNION=$MEMORY/union
DATAMNT=$MEMORY/data
BUNDLES=$MEMORY/bundles

header "ALSY-LIVE-KIT INIT <https://github.com/semsv/alsylinux/tree/master/alsy_live_kit/>"
init_proc_sysfs
debug_start                                                           
init_devs
init_aufs
# find data dir with filesystem bundles
DATA="$(find_data 60 "$DATAMNT")"                          
# init aufs union
init_union "$CHANGES" "$UNION"                             
# add data to union
union_append_bundles "$DATA" "$BUNDLES" "$UNION"           
# rootcopy
copy_rootcopy_content "$DATA" "$UNION"

# create empty fstab
fstab_create "$UNION"
                                                           
header "Live Kit done, starting $LIVEKITNAME"
change_root "$UNION"

header "!!ERROR occured, you shouldn't be here.!!"
/bin/sh
